#!/bin/bash

# 获取当前脚本所在的目录
basepath=$(cd `dirname $0`; pwd)

# 检查是否在源代码环境中
if [[ -d "$basepath/tapflow" ]]; then
    # 源代码环境
    source_path="$basepath/tapflow"
    # 检查并创建虚拟环境
    if [[ ! -d ".venv" ]]; then
        python3 -m venv .venv
        source .venv/bin/activate
        pip3 install -r requirements.txt
    fi
    source .venv/bin/activate
else
    # 安装后的环境，动态获取安装路径
    source_path=$(python3 -c "import os, tapflow; print(os.path.dirname(tapflow.__file__))")
fi

# 设置环境变量, 兼容 macos 和 linux
export LC_ALL="en_US.utf8" 2>/dev/null

# 运行 tap.py 脚本
python3 tapflow/cli/tap.py
