name: Package Binaries

on:
  push:
    tags:
      - 'v*'  # 当推送版本标签时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  # 二进制文件构建任务
  build-and-publish:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x86_64
          - os: macos-latest
            platform: darwin
            arch: x86_64
          - os: windows-latest
            platform: windows
            arch: x86_64

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: x64

      - name: Extract version from tag
        id: get_version
        shell: bash
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          else
            echo "VERSION=latest" >> $GITHUB_ENV
          fi

      - name: Install make (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install make
          
      - name: Build binary
        run: |
          make clean setup current

      - name: Generate checksum
        shell: bash
        run: |
          cd dist
          sha256sum * > SHA256SUMS.txt

      - name: Deploy to rsync server
        uses: Burnett01/rsync-deployments@6.0.0
        with:
          switches: -tvzr --delete
          path: dist/
          remote_path: /data/enterprise-artifact/gz/tapflow/${{ env.VERSION }}/
          remote_host: ${{ secrets.RSYNC_HOST }}
          remote_user: ${{ secrets.RSYNC_USER }}
          remote_key: ${{ secrets.RSYNC_PASSWORD }} 