name: Publish Package and Binaries

on:
  push:
    tags:
      - 'v*'  # 当推送版本标签时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  # PyPI 发布任务
  deploy-pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Extract version from tag
      id: get_version
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        else
          echo "VERSION=latest" >> $GITHUB_ENV
        fi

    - name: Update version in setup.py
      run: |
        sed -i "s/version='.*'/version='$VERSION'/g" setup.py
    
    - name: Build package
      run: python -m build
    
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*

  # 二进制文件构建任务
  build-binaries:
    needs: deploy-pypi
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x86_64
            ext: ""
          - os: macos-latest
            platform: darwin
            arch: x86_64
            ext: ""

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          architecture: x64

      - name: Extract version from tag
        id: get_version
        shell: bash
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          else
            echo "VERSION=latest" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Create config directory (Unix)
        run: mkdir -p ~/.tapflow

      - name: Build binary
        run: |
          python -m PyInstaller \
            --clean \
            --name tapflow-${{ env.VERSION }}-${{ matrix.platform }}-${{ matrix.arch }} \
            --add-data "requirements.txt:." \
            --add-data "README.md:." \
            --add-data "tapflow/cli/cli.py:tapflow/cli" \
            --add-data "etc:etc" \
            --add-data "tapflow:tapflow" \
            --hidden-import tapflow \
            --hidden-import tapflow.cli \
            --hidden-import tapflow.cli.cli \
            --hidden-import tapflow.cli.tap \
            --hidden-import tapflow.lib \
            --hidden-import tapflow.lib.configuration \
            --hidden-import tapflow.lib.configuration.config \
            --hidden-import tapflow.lib.backend_apis \
            --hidden-import tapflow.lib.data_pipeline \
            --hidden-import tapflow.lib.connections \
            --hidden-import tapflow.lib.utils \
            --hidden-import tapflow.lib.params \
            --hidden-import tapflow.lib.data_pipeline.validation \
            --hidden-import tapflow.lib.data_services \
            --hidden-import tapflow.lib.system \
            --hidden-import tapflow.lib.cache \
            --hidden-import tapflow.lib.backend_apis.common \
            --hidden-import tapflow.lib.backend_apis.connections \
            --hidden-import tapflow.lib.backend_apis.task \
            --hidden-import tapflow.lib.backend_apis.dataVerify \
            --hidden-import tapflow.lib.backend_apis.metadataInstance \
            --hidden-import tapflow.lib.backend_apis.apiServers \
            --hidden-import IPython \
            --hidden-import yaml \
            --hidden-import requests \
            --hidden-import websockets \
            --hidden-import bson \
            --hidden-import urllib \
            --hidden-import traitlets \
            --hidden-import importlib.metadata \
            --hidden-import logging \
            --hidden-import email \
            --hidden-import xml \
            --hidden-import http \
            --hidden-import ctypes \
            --hidden-import multiprocessing \
            --hidden-import dateutil \
            --hidden-import json \
            --hidden-import asyncio \
            --hidden-import concurrent.futures \
            --hidden-import idna \
            --hidden-import urllib3 \
            --hidden-import charset_normalizer \
            --log-level ERROR \
            --onefile \
            tapflow/cli/tap.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.platform }}-${{ matrix.arch }}
          path: dist/*${{ matrix.ext }}
          retention-days: 1

  # 发布二进制文件到服务器任务
  publish-binaries:
    needs: [build-binaries]
    runs-on: ubuntu-latest
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Install rsync
        run: sudo apt-get install -y rsync

      - name: Get version from tag
        id: get_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          else
            echo "VERSION=latest" >> $GITHUB_OUTPUT
          fi

      - name: Prepare artifacts for upload
        run: |
          mkdir -p upload
          cp -r dist/*/* upload/
          cd upload
          # 为每个文件添加 SHA256 校验和
          sha256sum * > SHA256SUMS.txt

      - name: Upload to server via rsync
        env:
          RSYNC_PASSWORD: ${{ secrets.RSYNC_PASSWORD }}
          RSYNC_HOST: ${{ secrets.RSYNC_HOST }}
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          rsync -avz --progress upload/ "rsync://${RSYNC_HOST}/data/enterprise-artifact/gz/tapflow/${VERSION}/"